//
//  QRCodeReaderRouter.swift
//  GistCommenter
//
//  Created Bruno Gama on 21/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Moya
import UIKit

internal class QRCodeReaderRouter: QRCodeReaderWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> QRCodeReaderViewController {

        let view = QRCodeReaderViewController.instantiate()
        let interactor = QRCodeReaderInteractor()
        interactor.codeReader = QRCodeReder()
        let router = QRCodeReaderRouter()
        let presenter = QRCodeReaderPresenter(interface: view, interactor: interactor, router: router)
        let client = Client(provider: MoyaProvider<GistService>())
        client?.remoteRequestHandler = interactor
        view.presenter = presenter
        interactor.presenter = presenter
        interactor.remoteDataManager = client
        router.viewController = view
        return view
    }

    func presentGistInformation(from view: QRCodeReaderViewProtocol?, gist: GistModel) {
        if let sourceView = view as? UIViewController {
            let detinationView = GistDetailRouter.createModule(gist: gist)
            sourceView.navigationController?.pushViewController(detinationView, animated: true)
        }
    }
}
