//
//  FileDetailProtocols.swift
//  GistCommenter
//
//  Created Bruno Gama on 25/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
internal protocol FileDetailWireframeProtocol: class {

}
// MARK: Presenter -
internal protocol FileDetailPresenterProtocol: class {

}

// MARK: Interactor -
internal protocol FileDetailInteractorProtocol: class {

  var presenter: FileDetailPresenterProtocol? { get set }
}

// MARK: View -
internal protocol FileDetailViewProtocol: class {

  var presenter: FileDetailPresenterProtocol? { get set }
}
