//
//  FileDetailViewController.swift
//  GistCommenter
//
//  Created Bruno Gama on 25/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Highlightr
import UIKit

internal final class FileDetailViewController: UIViewController, FileDetailViewProtocol {

    @IBOutlet private  weak var editorTextView: UITextView!
    var presenter: FileDetailPresenterProtocol?
    var file: FileModel?

    override func viewDidLoad() {
        super.viewDidLoad()

        guard let highlightr = Highlightr() else {
            fatalError("Highlightr not loaded")
        }

        highlightr.setTheme(to: "paraiso-dark")
        if let code = file?.content {
            let highlightedCode = highlightr.highlight(code)
            editorTextView.attributedText = highlightedCode
        }
    }

    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
}
