//
//  FileDetailRouter.swift
//  GistCommenter
//
//  Created Bruno Gama on 25/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

internal final class FileDetailRouter: FileDetailWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(fileModel: FileModel) -> UIViewController {
        let view = FileDetailViewController(nibName: nil, bundle: nil)
        let interactor = FileDetailInteractor()
        let router = FileDetailRouter()
        let presenter = FileDetailPresenter(interface: view, interactor: interactor, router: router)
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
