//
//  FileDetailInteractor.swift
//  GistCommenter
//
//  Created Bruno Gama on 25/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

internal final class FileDetailInteractor: FileDetailInteractorProtocol {

    weak var presenter: FileDetailPresenterProtocol?

}
