//
//  FileDetailPresenter.swift
//  GistCommenter
//
//  Created Bruno Gama on 25/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

internal final class FileDetailPresenter: FileDetailPresenterProtocol {

    weak private var view: FileDetailViewProtocol?
    var interactor: FileDetailInteractorProtocol?
    private let router: FileDetailWireframeProtocol

    init(interface: FileDetailViewProtocol,
         interactor: FileDetailInteractorProtocol?,
         router: FileDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
