//
//  GistDetailViewController.swift
//  GistCommenter
//
//  Created Bruno Gama on 23/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import SkeletonView
import UIKit

internal final class GistDetailViewController: UIViewController, GistDetailViewProtocol {

	var presenter: GistDetailPresenterProtocol?
    var datasource: (GistDetailDatasourceProtocol & UITableViewDataSource)?

    @IBOutlet private weak var tableView: UITableView!
//    private var headerView: GistView = GistView()

    // MARK: - View life cycle
	override func viewDidLoad() {
        super.viewDidLoad()

        title = "Gist Detail"
        navigationItem.title = title
        tableView.register(cellType: GistCommentTableViewCell.self)
        tableView.dataSource = datasource
        tableView.tableFooterView = UIView()
        tableView.separatorInset = .zero
        presenter?.viewDidLoad()
    }

    // MARK: - GistDetailViewProtocol
    func show(comments: [GistComment]) {
        datasource?.data.value = comments
        hideLoading()
    }

    func loading() {
    }

    func hideLoading() {
        tableView.reloadData()
        tableView.flashScrollIndicators()
    }
}

extension UITableView {
    func updatesViews(block: () -> Void) {
        beginUpdates()
        block()
        endUpdates()
    }
}
