//
//  GistDetailViewController.swift
//  GistCommenter
//
//  Created Bruno Gama on 23/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

internal final class GistDetailViewController: UIViewController, UITableViewDelegate, GistDetailViewProtocol {
    
	var presenter: GistDetailPresenterProtocol?
    var datasource: (GistDetailDatasourceProtocol & UITableViewDataSource)?

    @IBOutlet private weak var tableView: UITableView!
    private var tableHeaderView: GistHeaderView?
    private var alertController: UIAlertController?

    // MARK: - View life cycle
    override func viewDidLoad() {
        super.viewDidLoad()

        title = datasource?.title

        setupNavigationBar()
        setupTableView()
        presenter?.viewDidLoad()
    }

    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }

    func tableView(_ tableView: UITableView, viewForFooterInSection section: Int) -> UIView? {
        return UIView.zero()
    }

    func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
        return 0
    }

    func tableView(_ tableView: UITableView,
                   heightForHeaderInSection section: Int) -> CGFloat {
        return 44
    }

    func tableView(_ tableView: UITableView,
                   viewForHeaderInSection section: Int) -> UIView? {
        let frame = CGRect(x: 0, y: 0, width: tableView.bounds.size.width,
                           height: self.tableView(tableView, heightForHeaderInSection: section))
        let view = GistHeaderView(frame: frame)
        view.title = section == 0 ? "Files inside the Gist" : "Comments"
        return view
    }

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if let file = datasource?[file: indexPath.row] {
            presenter?.openFileDetailsView(file: file)
            return
        }
    }

    // MARK: - GistDetailViewProtocol
    func show(comments: [GistComment]) {
        datasource?.data.value = comments
        hideLoading()
        tableView.reloadData()
    }

    func loading() {
        cleanTableFooterView()

        let activityViewSize = CGFloat(44)
        let tableFooterViewHeight = activityViewSize * 1.4
        let width = tableView.frame.size.width

        let footerViewFrame = CGRect(x: 0, y: 0, width: width, height: tableFooterViewHeight)
        let tableFooterView = UIView(frame: footerViewFrame)

        let indicatorView = activityIndicatorView(with: activityViewSize)
        tableFooterView.addSubview(indicatorView)
        addCenteringConstraints(indicatorView)
        tableView.tableFooterView = tableFooterView
        tableView.tableFooterView?.frame = tableFooterView.frame
    }

    func hideLoading() {
        cleanTableFooterView()
        tableView.reloadData()
        tableView.flashScrollIndicators()
    }

    func cleanTableFooterView() {
        tableView.tableFooterView?.subviews.flatMap { $0 as UIView }.forEach { $0.removeFromSuperview() }
        tableView.tableFooterView = UIView.zero()
    }

    func presentEmpty() {
        datasource?.data.value = []
        hideLoading()
        cleanTableFooterView()
        let text = L10n.noComments
        let label = emptyLabel(with: text)
        tableView.tableFooterView = label
        tableView.tableFooterView?.frame = CGRect(x: 0, y: 0, width: tableView.frame.size.width, height: 44)
        tableView.reloadData()
    }

    func requestCredentials() {
        let alert = UIAlertController(title: "Login required",
                                      message: nil,
                                      preferredStyle: .alert)
        let loginAction = UIAlertAction(title: "Log In", style: .default) { _ -> Void in

            guard let login = alert.textFields?[0].text,
                  let password = alert.textFields?[1].text else {
                    fatalError("Fields or Texts not found")
            }

            self.presenter?.authenticateWith(username: login, password: password)
        }

        let cancelAction = UIAlertAction(title: "Cancel", style: .default)

//        loginAction.isEnabled = false

        alert.addTextField { textField -> Void in
            textField.placeholder = "Username"
        }

        alert.addTextField { textField -> Void in
            textField.placeholder = "Password"
            textField.isSecureTextEntry = true
        }

        alert.addAction(loginAction)
        alert.addAction(cancelAction)

        self.present(alert, animated: true)
    }

    func presentMessageInput() {

        let alert = UIAlertController(title: "Write your message",
                                      message: nil,
                                      preferredStyle: .alert)
        let submitMessageAction = UIAlertAction(title: L10n.send, style: .default) { _ -> Void in

            guard let message = alert.textFields?[0].text,
                  let gistId = self.datasource?.gistModel.id else {
                    fatalError("Fields or Texts not found")
            }
            self.presenter?.sendMessageFor(gistId: gistId, message: message)
        }

        let cancelAction = UIAlertAction(title: L10n.cancel, style: .cancel)

        submitMessageAction.isEnabled = false

        alert.addTextField { textField -> Void in
            textField.placeholder = L10n.message
        }

        alert.addAction(submitMessageAction)
        alert.addAction(cancelAction)

        if self.alertController?.isBeingPresented ?? false {
            self.alertController?.dismiss(animated: true) {
                self.present(alert, animated: true)
            }
        }
        else {
            self.present(alert, animated: true)
        }

        self.alertController = alert
    }
    func messageSent(message: GistComment) {
        
        self.datasource?.data.value.append(message)

        let alert = UIAlertController(
            title: "Success",
            message: "Message sent",
            preferredStyle: .alert
        )

        let action = UIAlertAction(title: L10n.ok, style: .default) { _ in
            self.tableView.reloadData()
        }

        alert.addAction(action)
        self.alertController?.dismiss(animated: true) {
            self.present(alert, animated: true) {
                self.alertController = nil
            }
        }
    }
    func messageFail() {
        let alert = UIAlertController(
            title: "Atention",
            message: "Failed sending message",
            preferredStyle: .alert
        )

        alert.addAction(UIAlertAction(title: L10n.ok, style: .default))
        self.alertController?.dismiss(animated: true) {
            self.present(alert, animated: true) {
                self.alertController = nil
            }
        }
    }

    func sendingMessage() {
        let alert = UIAlertController.loading(L10n.sendingMessage)
        self.present(alert, animated: true)
        self.alertController = alert
    }

    func authenticating() {
        let alert = UIAlertController.loading(L10n.requestingToken)
        self.present(alert, animated: true)
        self.alertController = alert
    }

    func authenticationFail() {
        let alert = UIAlertController(
            title: "Atention",
            message: L10n.tokenRequestFailed,
            preferredStyle: .alert
        )

        alert.addAction(UIAlertAction(title: L10n.ok, style: .default))
        self.alertController?.dismiss(animated: true) {
            self.present(alert, animated: true) {
                self.alertController = nil
            }
        }
    }

    @objc func prepareToSendMessage() {
        presenter?.authenticateOrSendMessageAction()
    }

    // MARK: Private methods
    fileprivate func setupTableView() {
        tableView.register(cellType: CommentTableViewCell.self)
        tableView.register(cellType: FileCell.self)
        tableView.rowHeight = UITableViewAutomaticDimension
        tableView.estimatedRowHeight = 44
        tableView.dataSource = datasource
        tableView.delegate = self
        tableView.tableFooterView = UIView.zero()
        tableView.separatorInset = .zero
        tableView.separatorColor = Asset.Colors.lightGray.color.withAlphaComponent(0.5)
        tableView.reloadData()
    }

    fileprivate func setupNavigationBar() {
//        navigationItem.title = title
//        navigationItem.prompt = L10n.gistDetail
        navigationItem.prompt = title
        navigationItem.rightBarButtonItem = UIBarButtonItem(
            image: #imageLiteral(resourceName: "message-square"),
            landscapeImagePhone: nil,
            style: .plain,
            target: self,
            action: #selector(prepareToSendMessage)
        )
    }

    fileprivate func add(visualConstraints: [String], to views: [String: Any]) {
        visualConstraints.forEach { format in
            NSLayoutConstraint.constraints(withVisualFormat: format, options: .init(rawValue:0), metrics: nil,
                                           views: views).forEach { $0.isActive = true }
        }
    }

    fileprivate func addCenteringConstraints(_ toView: UIView) {
        toView.translatesAutoresizingMaskIntoConstraints = false
        add(visualConstraints: ["H:|[view]|", "V:|[view]|"], to: ["view": toView])
    }

    fileprivate func activityIndicatorView(with size: CGFloat) -> UIActivityIndicatorView {
        let activityIndicatiorViewFrame = CGRect(x: 0, y: 0, width: size, height: size)
        let activityIndicatiorView = UIActivityIndicatorView(frame: activityIndicatiorViewFrame)
        activityIndicatiorView.activityIndicatorViewStyle = .gray
        activityIndicatiorView.startAnimating()

        return activityIndicatiorView
    }

    fileprivate func emptyLabel(with text: String) -> UILabel {
        let emptyLabel = UILabel()
        emptyLabel.text = text
        emptyLabel.textColor = Asset.Colors.darkGray.color
        emptyLabel.sizeToFit()
        emptyLabel.textAlignment = .center

        return emptyLabel
    }
}

extension UITableView {
    func updatesViews(block: () -> Void) {
        beginUpdates()
        block()
        endUpdates()
    }
}

extension UIView {
    static func zero() -> UIView { return self.init(frame: CGRect.zero ) }
}
