//
//  GistDetailRouter.swift
//  GistCommenter
//
//  Created Bruno Gama on 23/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import  Moya
import UIKit

internal final class GistDetailRouter: GistDetailWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule(gist: GistModel) -> UIViewController {

        guard let url = Bundle.main.url(forResource: "gist", withExtension: "json"),
            let data = try? Data(contentsOf: url) else {
                fatalError("Bundle not loaded")
        }

        let dataSource = GistDetailDatasource(gistModel: GistModel(data: data)!)

        let view = GistDetailViewController.instantiate()
        view.datasource = dataSource

        let interactor = GistDetailInteractor()
        let client = Client(provider: MoyaProvider<GistService>())
        client?.remoteRequestHandler = interactor

        interactor.remoteDataManager = client

        let router = GistDetailRouter()
        let presenter = GistDetailPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }

    func presentDetailView(from view: GistDetailViewProtocol?, file: FileModel) {
        if let sourceView = view as? UIViewController {
            let detinationView = FileDetailRouter.createModule(fileModel: file)
            sourceView.navigationController?.pushViewController(detinationView, animated: true)
        }
    }
}
