//
//  GistDetailPresenter.swift
//  GistCommenter
//
//  Created Bruno Gama on 23/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Moya
import UIKit

internal class GistDetailPresenter: GistDetailPresenterProtocol, GistDetailInteractorOutputProtocol {

    weak private var view: GistDetailViewProtocol?
    var interactor: GistDetailInteractorInputProtocol?
    private let router: GistDetailWireframeProtocol

    init(interface: GistDetailViewProtocol,
         interactor: GistDetailInteractorInputProtocol?,
         router: GistDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    // MARK: - GistDetailPresenterProtocol

    func viewDidLoad() {
        view?.loading()
        let gistId: GistId = "711b5553533d1a14364907bbcdbee677"
        interactor?.retrieveComments(fromGistId: (view?.datasource?.gistModel.id)!)
    }

    // MARK: - GistDetailInteractorOutputProtocol
    func didReceived(comments: [GistComment]) {
        view?.show(comments: comments)
    }

}
