//
//  GistDetailViewController.swift
//  GistCommenter
//
//  Created Bruno Gama on 23/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

internal final class GistDetailViewController: UIViewController, GistDetailViewProtocol {

	var presenter: GistDetailPresenterProtocol?

    // MARK: - View life cycle
	override func viewDidLoad() {
        super.viewDidLoad()
    }

    // MARK: - GistDetailViewProtocol
}
