//
//  GistDetailRouter.swift
//  GistCommenter
//
//  Created Bruno Gama on 23/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import  Moya
import UIKit

internal final class GistDetailRouter: GistDetailWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {

        guard let url = Bundle.main.url(forResource: "gist", withExtension: "json"),
            let data = try? Data(contentsOf: url) else {
                fatalError("Bundle not loaded")
        }

        let dataSource = GistDetailDatasource(gistModel: GistModel(data: data)!)

        let view = GistDetailViewController.instantiate()
        view.datasource = dataSource

        let interactor = GistDetailInteractor()
        interactor.remoteDataManager = MoyaProvider()

        let router = GistDetailRouter()
        let presenter = GistDetailPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }

    func showRaw(gist: GistModel) {
        guard let urlString = gist.files.first?.value.rawURL,
              let url = URL(string: urlString) else {
            fatalError("Invalid url")
        }

        UIApplication.shared.open(url, options: [:])
    }
}
