//
//  GistDetailViewController.swift
//  GistCommenter
//
//  Created Bruno Gama on 23/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Moya
import UIKit

internal final class GistDetailViewController: UIViewController, GistDetailViewProtocol {

	var presenter: GistDetailPresenterProtocol?

    // MARK: - View life cycle
	override func viewDidLoad() {
        super.viewDidLoad()

        title = "Gist Detail"
        presenter?.interactor?.remoteDataManager = MoyaProvider()
        let urlString = "https://gist.github.com/brunogama/a3f7520c9727bc3d134818658fcae5dd"
        presenter?.interactor?.requestGistModel(url: URL(string: urlString)!)
    }

    // MARK: - GistDetailViewProtocol
}
