//
//  GistDetailProtocols.swift
//  GistCommenter
//
//  Created Bruno Gama on 23/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
internal protocol GistDetailWireframeProtocol: class {

}

// MARK: Presenter -
internal protocol GistDetailPresenterProtocol: class {

    var interactor: GistDetailInteractorInputProtocol? { get set }
}

// MARK: Interactor -
internal protocol GistDetailInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

internal protocol GistDetailInteractorInputProtocol: class {

    var presenter: GistDetailInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
}

// MARK: View -
internal protocol GistDetailViewProtocol: class {

    var presenter: GistDetailPresenterProtocol? { get set }

    /* Presenter -> ViewController */
}
