//
//  GistDetailInteractor.swift
//  GistCommenter
//
//  Created Bruno Gama on 23/03/2018.
//  Copyright © 2018 Bruno Gama. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Moya
import UIKit

internal final class GistDetailInteractor: GistDetailInteractorInputProtocol {

    weak var presenter: GistDetailInteractorOutputProtocol?
    var remoteDataManager: MoyaProvider<GistService>?

    func retrieveComments(with gistId: GistId) { }

    func requestGistModel(url: URL) {
    }

    func didReceived(comments: [GistComment]) {
        presenter?.didReceived(comments: comments)
    }
}
